<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'dial_code' => '+93', 'currency_code' => 'AFN'],
            ['name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'dial_code' => '+355', 'currency_code' => 'ALL'],
            ['name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'dial_code' => '+213', 'currency_code' => 'DZD'],
            ['name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'dial_code' => '+376', 'currency_code' => 'EUR'],
            ['name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'dial_code' => '+244', 'currency_code' => 'AOA'],
            ['name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'dial_code' => '+1', 'currency_code' => 'XCD'],
            ['name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'dial_code' => '+54', 'currency_code' => 'ARS'],
            ['name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'dial_code' => '+374', 'currency_code' => 'AMD'],
            ['name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'dial_code' => '+61', 'currency_code' => 'AUD'],
            ['name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'dial_code' => '+43', 'currency_code' => 'EUR'],
            ['name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'dial_code' => '+994', 'currency_code' => 'AZN'],
            ['name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'dial_code' => '+1', 'currency_code' => 'BSD'],
            ['name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'dial_code' => '+973', 'currency_code' => 'BHD'],
            ['name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'dial_code' => '+880', 'currency_code' => 'BDT'],
            ['name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'dial_code' => '+1', 'currency_code' => 'BBD'],
            ['name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'dial_code' => '+375', 'currency_code' => 'BYN'],
            ['name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'dial_code' => '+32', 'currency_code' => 'EUR'],
            ['name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'dial_code' => '+501', 'currency_code' => 'BZD'],
            ['name' => 'Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'dial_code' => '+229', 'currency_code' => 'XOF'],
            ['name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'dial_code' => '+975', 'currency_code' => 'BTN'],
            ['name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'dial_code' => '+591', 'currency_code' => 'BOB'],
            ['name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'dial_code' => '+387', 'currency_code' => 'BAM'],
            ['name' => 'Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'dial_code' => '+267', 'currency_code' => 'BWP'],
            ['name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'dial_code' => '+55', 'currency_code' => 'BRL'],
            ['name' => 'Brunei', 'iso2' => 'BN', 'iso3' => 'BRN', 'dial_code' => '+673', 'currency_code' => 'BND'],
            ['name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'dial_code' => '+359', 'currency_code' => 'BGN'],
            ['name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'dial_code' => '+226', 'currency_code' => 'XOF'],
            ['name' => 'Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'dial_code' => '+257', 'currency_code' => 'BIF'],
            ['name' => 'Cabo Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'dial_code' => '+238', 'currency_code' => 'CVE'],
            ['name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'dial_code' => '+855', 'currency_code' => 'KHR'],
            ['name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'dial_code' => '+237', 'currency_code' => 'XAF'],
            ['name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'dial_code' => '+1', 'currency_code' => 'CAD'],
            ['name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'dial_code' => '+236', 'currency_code' => 'XAF'],
            ['name' => 'Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'dial_code' => '+235', 'currency_code' => 'XAF'],
            ['name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'dial_code' => '+56', 'currency_code' => 'CLP'],
            ['name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'dial_code' => '+86', 'currency_code' => 'CNY'],
            ['name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'dial_code' => '+57', 'currency_code' => 'COP'],
            ['name' => 'Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'dial_code' => '+269', 'currency_code' => 'KMF'],
            ['name' => 'Congo (Brazzaville)', 'iso2' => 'CG', 'iso3' => 'COG', 'dial_code' => '+242', 'currency_code' => 'XAF'],
            ['name' => 'Congo (Kinshasa)', 'iso2' => 'CD', 'iso3' => 'COD', 'dial_code' => '+243', 'currency_code' => 'CDF'],
            ['name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'dial_code' => '+506', 'currency_code' => 'CRC'],
            ['name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'dial_code' => '+385', 'currency_code' => 'EUR'],
            ['name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'dial_code' => '+53', 'currency_code' => 'CUP'],
            ['name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'dial_code' => '+357', 'currency_code' => 'EUR'],
            ['name' => 'Czech Republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'dial_code' => '+420', 'currency_code' => 'CZK'],
            ['name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'dial_code' => '+45', 'currency_code' => 'DKK'],
            ['name' => 'Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'dial_code' => '+253', 'currency_code' => 'DJF'],
            ['name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'dial_code' => '+1', 'currency_code' => 'XCD'],
            ['name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'dial_code' => '+1', 'currency_code' => 'DOP'],
            ['name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'dial_code' => '+593', 'currency_code' => 'USD'],
            ['name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'dial_code' => '+20', 'currency_code' => 'EGP'],
            ['name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'dial_code' => '+503', 'currency_code' => 'USD'],
            ['name' => 'Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'dial_code' => '+240', 'currency_code' => 'XAF'],
            ['name' => 'Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'dial_code' => '+291', 'currency_code' => 'ERN'],
            ['name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'dial_code' => '+372', 'currency_code' => 'EUR'],
            ['name' => 'Eswatini', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'dial_code' => '+268', 'currency_code' => 'SZL'],
            ['name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'dial_code' => '+251', 'currency_code' => 'ETB'],
            ['name' => 'Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'dial_code' => '+679', 'currency_code' => 'FJD'],
            ['name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'dial_code' => '+358', 'currency_code' => 'EUR'],
            ['name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'dial_code' => '+33', 'currency_code' => 'EUR'],
            ['name' => 'Gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'dial_code' => '+241', 'currency_code' => 'XAF'],
            ['name' => 'Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'dial_code' => '+220', 'currency_code' => 'GMD'],
            ['name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'dial_code' => '+995', 'currency_code' => 'GEL'],
            ['name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'dial_code' => '+49', 'currency_code' => 'EUR'],
            ['name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'dial_code' => '+233', 'currency_code' => 'GHS'],
            ['name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'dial_code' => '+30', 'currency_code' => 'EUR'],
            ['name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'dial_code' => '+1', 'currency_code' => 'XCD'],
            ['name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'dial_code' => '+502', 'currency_code' => 'GTQ'],
            ['name' => 'Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'dial_code' => '+224', 'currency_code' => 'GNF'],
            ['name' => 'Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'dial_code' => '+245', 'currency_code' => 'XOF'],
            ['name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'dial_code' => '+592', 'currency_code' => 'GYD'],
            ['name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'dial_code' => '+509', 'currency_code' => 'HTG'],
            ['name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'dial_code' => '+504', 'currency_code' => 'HNL'],
            ['name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'dial_code' => '+36', 'currency_code' => 'HUF'],
            ['name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'dial_code' => '+354', 'currency_code' => 'ISK'],
            ['name' => 'India', 'iso2' => 'IN', 'iso3' => 'IND', 'dial_code' => '+91', 'currency_code' => 'INR'],
            ['name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'dial_code' => '+62', 'currency_code' => 'IDR'],
            ['name' => 'Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'dial_code' => '+98', 'currency_code' => 'IRR'],
            ['name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'dial_code' => '+964', 'currency_code' => 'IQD'],
            ['name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'dial_code' => '+353', 'currency_code' => 'EUR'],
            ['name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'dial_code' => '+972', 'currency_code' => 'ILS'],
            ['name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'dial_code' => '+39', 'currency_code' => 'EUR'],
            ['name' => 'Ivory Coast', 'iso2' => 'CI', 'iso3' => 'CIV', 'dial_code' => '+225', 'currency_code' => 'XOF'],
            ['name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'dial_code' => '+1', 'currency_code' => 'JMD'],
            ['name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'dial_code' => '+81', 'currency_code' => 'JPY'],
            ['name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'dial_code' => '+962', 'currency_code' => 'JOD'],
            ['name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'dial_code' => '+7', 'currency_code' => 'KZT'],
            ['name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'dial_code' => '+254', 'currency_code' => 'KES'],
            ['name' => 'Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'dial_code' => '+686', 'currency_code' => 'AUD'],
            ['name' => 'Kosovo', 'iso2' => 'XK', 'iso3' => 'XKX', 'dial_code' => '+383', 'currency_code' => 'EUR'],
            ['name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'dial_code' => '+965', 'currency_code' => 'KWD'],
            ['name' => 'Kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'dial_code' => '+996', 'currency_code' => 'KGS'],
            ['name' => 'Laos', 'iso2' => 'LA', 'iso3' => 'LAO', 'dial_code' => '+856', 'currency_code' => 'LAK'],
            ['name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'dial_code' => '+371', 'currency_code' => 'EUR'],
            ['name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'dial_code' => '+961', 'currency_code' => 'LBP'],
            ['name' => 'Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'dial_code' => '+266', 'currency_code' => 'LSL'],
            ['name' => 'Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'dial_code' => '+231', 'currency_code' => 'LRD'],
            ['name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'dial_code' => '+218', 'currency_code' => 'LYD'],
            ['name' => 'Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'dial_code' => '+423', 'currency_code' => 'CHF'],
            ['name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'dial_code' => '+370', 'currency_code' => 'EUR'],
            ['name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'dial_code' => '+352', 'currency_code' => 'EUR'],
            ['name' => 'Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'dial_code' => '+261', 'currency_code' => 'MGA'],
            ['name' => 'Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'dial_code' => '+265', 'currency_code' => 'MWK'],
            ['name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'dial_code' => '+60', 'currency_code' => 'MYR'],
            ['name' => 'Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'dial_code' => '+960', 'currency_code' => 'MVR'],
            ['name' => 'Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'dial_code' => '+223', 'currency_code' => 'XOF'],
            ['name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'dial_code' => '+356', 'currency_code' => 'EUR'],
            ['name' => 'Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'dial_code' => '+692', 'currency_code' => 'USD'],
            ['name' => 'Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'dial_code' => '+222', 'currency_code' => 'MRU'],
            ['name' => 'Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'dial_code' => '+230', 'currency_code' => 'MUR'],
            ['name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'dial_code' => '+52', 'currency_code' => 'MXN'],
            ['name' => 'Micronesia', 'iso2' => 'FM', 'iso3' => 'FSM', 'dial_code' => '+691', 'currency_code' => 'USD'],
            ['name' => 'Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'dial_code' => '+373', 'currency_code' => 'MDL'],
            ['name' => 'Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'dial_code' => '+377', 'currency_code' => 'EUR'],
            ['name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'dial_code' => '+976', 'currency_code' => 'MNT'],
            ['name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'dial_code' => '+382', 'currency_code' => 'EUR'],
            ['name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'dial_code' => '+212', 'currency_code' => 'MAD'],
            ['name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'dial_code' => '+258', 'currency_code' => 'MZN'],
            ['name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'dial_code' => '+95', 'currency_code' => 'MMK'],
            ['name' => 'Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'dial_code' => '+264', 'currency_code' => 'NAD'],
            ['name' => 'Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'dial_code' => '+674', 'currency_code' => 'AUD'],
            ['name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'dial_code' => '+977', 'currency_code' => 'NPR'],
            ['name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'dial_code' => '+31', 'currency_code' => 'EUR'],
            ['name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'dial_code' => '+64', 'currency_code' => 'NZD'],
            ['name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'dial_code' => '+505', 'currency_code' => 'NIO'],
            ['name' => 'Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'dial_code' => '+227', 'currency_code' => 'XOF'],
            ['name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'dial_code' => '+234', 'currency_code' => 'NGN'],
            ['name' => 'North Korea', 'iso2' => 'KP', 'iso3' => 'PRK', 'dial_code' => '+850', 'currency_code' => 'KPW'],
            ['name' => 'North Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'dial_code' => '+389', 'currency_code' => 'MKD'],
            ['name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'dial_code' => '+47', 'currency_code' => 'NOK'],
            ['name' => 'Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'dial_code' => '+968', 'currency_code' => 'OMR'],
            ['name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'dial_code' => '+92', 'currency_code' => 'PKR'],
            ['name' => 'Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'dial_code' => '+680', 'currency_code' => 'USD'],
            ['name' => 'Palestine', 'iso2' => 'PS', 'iso3' => 'PSE', 'dial_code' => '+970', 'currency_code' => 'ILS'],
            ['name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'dial_code' => '+507', 'currency_code' => 'PAB'],
            ['name' => 'Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'dial_code' => '+675', 'currency_code' => 'PGK'],
            ['name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'dial_code' => '+595', 'currency_code' => 'PYG'],
            ['name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'dial_code' => '+51', 'currency_code' => 'PEN'],
            ['name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'dial_code' => '+63', 'currency_code' => 'PHP'],
            ['name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'dial_code' => '+48', 'currency_code' => 'PLN'],
            ['name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'dial_code' => '+351', 'currency_code' => 'EUR'],
            ['name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'dial_code' => '+974', 'currency_code' => 'QAR'],
            ['name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'dial_code' => '+40', 'currency_code' => 'RON'],
            ['name' => 'Russia', 'iso2' => 'RU', 'iso3' => 'RUS', 'dial_code' => '+7', 'currency_code' => 'RUB'],
            ['name' => 'Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'dial_code' => '+250', 'currency_code' => 'RWF'],
            ['name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'dial_code' => '+1', 'currency_code' => 'XCD'],
            ['name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'dial_code' => '+1', 'currency_code' => 'XCD'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'dial_code' => '+1', 'currency_code' => 'XCD'],
            ['name' => 'Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'dial_code' => '+685', 'currency_code' => 'WST'],
            ['name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'dial_code' => '+378', 'currency_code' => 'EUR'],
            ['name' => 'Sao Tome and Principe', 'iso2' => 'ST', 'iso3' => 'STP', 'dial_code' => '+239', 'currency_code' => 'STN'],
            ['name' => 'Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'dial_code' => '+966', 'currency_code' => 'SAR'],
            ['name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'dial_code' => '+221', 'currency_code' => 'XOF'],
            ['name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'dial_code' => '+381', 'currency_code' => 'RSD'],
            ['name' => 'Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'dial_code' => '+248', 'currency_code' => 'SCR'],
            ['name' => 'Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'dial_code' => '+232', 'currency_code' => 'SLL'],
            ['name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'dial_code' => '+65', 'currency_code' => 'SGD'],
            ['name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'dial_code' => '+421', 'currency_code' => 'EUR'],
            ['name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'dial_code' => '+386', 'currency_code' => 'EUR'],
            ['name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'dial_code' => '+677', 'currency_code' => 'SBD'],
            ['name' => 'Somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'dial_code' => '+252', 'currency_code' => 'SOS'],
            ['name' => 'South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'dial_code' => '+27', 'currency_code' => 'ZAR'],
            ['name' => 'South Korea', 'iso2' => 'KR', 'iso3' => 'KOR', 'dial_code' => '+82', 'currency_code' => 'KRW'],
            ['name' => 'South Sudan', 'iso2' => 'SS', 'iso3' => 'SSD', 'dial_code' => '+211', 'currency_code' => 'SSP'],
            ['name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'dial_code' => '+34', 'currency_code' => 'EUR'],
            ['name' => 'Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'dial_code' => '+94', 'currency_code' => 'LKR'],
            ['name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'dial_code' => '+249', 'currency_code' => 'SDG'],
            ['name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'dial_code' => '+597', 'currency_code' => 'SRD'],
            ['name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'dial_code' => '+46', 'currency_code' => 'SEK'],
            ['name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'dial_code' => '+41', 'currency_code' => 'CHF'],
            ['name' => 'Syria', 'iso2' => 'SY', 'iso3' => 'SYR', 'dial_code' => '+963', 'currency_code' => 'SYP'],
            ['name' => 'Taiwan', 'iso2' => 'TW', 'iso3' => 'TWN', 'dial_code' => '+886', 'currency_code' => 'TWD'],
            ['name' => 'Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'dial_code' => '+992', 'currency_code' => 'TJS'],
            ['name' => 'Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'dial_code' => '+255', 'currency_code' => 'TZS'],
            ['name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'dial_code' => '+66', 'currency_code' => 'THB'],
            ['name' => 'Timor-Leste', 'iso2' => 'TL', 'iso3' => 'TLS', 'dial_code' => '+670', 'currency_code' => 'USD'],
            ['name' => 'Togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'dial_code' => '+228', 'currency_code' => 'XOF'],
            ['name' => 'Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'dial_code' => '+676', 'currency_code' => 'TOP'],
            ['name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'dial_code' => '+1', 'currency_code' => 'TTD'],
            ['name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'dial_code' => '+216', 'currency_code' => 'TND'],
            ['name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'dial_code' => '+90', 'currency_code' => 'TRY'],
            ['name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'dial_code' => '+993', 'currency_code' => 'TMT'],
            ['name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'dial_code' => '+688', 'currency_code' => 'AUD'],
            ['name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'dial_code' => '+256', 'currency_code' => 'UGX'],
            ['name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'dial_code' => '+380', 'currency_code' => 'UAH'],
            ['name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'dial_code' => '+971', 'currency_code' => 'AED'],
            ['name' => 'United Kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'dial_code' => '+44', 'currency_code' => 'GBP'],
            ['name' => 'United States', 'iso2' => 'US', 'iso3' => 'USA', 'dial_code' => '+1', 'currency_code' => 'USD'],
            ['name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'dial_code' => '+598', 'currency_code' => 'UYU'],
            ['name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'dial_code' => '+998', 'currency_code' => 'UZS'],
            ['name' => 'Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'dial_code' => '+678', 'currency_code' => 'VUV'],
            ['name' => 'Vatican City', 'iso2' => 'VA', 'iso3' => 'VAT', 'dial_code' => '+379', 'currency_code' => 'EUR'],
            ['name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'dial_code' => '+58', 'currency_code' => 'VES'],
            ['name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'dial_code' => '+84', 'currency_code' => 'VND'],
            ['name' => 'Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'dial_code' => '+967', 'currency_code' => 'YER'],
            ['name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'dial_code' => '+260', 'currency_code' => 'ZMW'],
            ['name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'dial_code' => '+263', 'currency_code' => 'ZWL'],
        ];

        $now = now();
        $chunks = array_chunk($countries, 50);

        foreach ($chunks as $chunk) {
            DB::table('countries')->upsert(
                array_map(fn($c) => array_merge($c, [
                    'is_active'  => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]), $chunk),
                ['iso2'],
                ['name', 'iso3', 'dial_code', 'currency_code', 'updated_at']
            );
        }

        $this->command->info('Countries seeded: ' . count($countries));
    }
}
